# Generated by Django 4.2.16 on 2026-08-28 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_id', models.CharField(max_length=100)),
                ('name', models.CharField(default='My Vamsapattika', max_length=255)),
                ('family_data', models.JSONField(default=dict)),
                ('next_id', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family Tree',
                'verbose_name_plural': 'Family Trees',
                'db_table': 'family_trees',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['user', 'tree_id'], name='family_tree_user_id_a98beb_idx'), models.Index(fields=['user', '-last_updated'], name='family_tree_user_id_60d93d_idx')],
                'unique_together': {('user', 'tree_id')},
            },
        ),
    ]
