# Generated by Django 4.2.16 on 2026-09-15 07:47

from django.db import migrations, models


def populate_transaction_ids_from_razorpay(apps, schema_editor):
    """Populate transaction IDs from Razorpay payment_id or order_id"""
    PaymentTransaction = apps.get_model('payments', 'PaymentTransaction')
    for transaction in PaymentTransaction.objects.all():
        # Use payment_id if available (completed payments), otherwise use order_id
        if transaction.razorpay_payment_id:
            transaction.transaction_id = transaction.razorpay_payment_id
        elif transaction.razorpay_order_id:
            transaction.transaction_id = transaction.razorpay_order_id
        else:
            # Should not happen, but handle edge case
            transaction.transaction_id = f"TXN_MISSING_{transaction.id}"
        transaction.save(update_fields=['transaction_id'])


def reverse_transaction_ids(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        # Step 1: Add field as nullable without unique constraint or index
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=100, null=True, blank=True, db_index=False),
        ),
        # Step 2: Populate existing records with Razorpay IDs
        migrations.RunPython(populate_transaction_ids_from_razorpay, reverse_transaction_ids),
        # Step 3: Make field non-nullable (without unique constraint yet)
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=100, db_index=False),
        ),
        # Step 4: Add unique constraint
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=100, unique=True, db_index=True),
        ),
    ]