# Generated by Django 4.2.16 on 2026-09-15 07:47

from django.db import migrations, models
import uuid


def generate_unique_transaction_ids(apps, schema_editor):
    """Generate unique transaction IDs for existing records"""
    PaymentTransaction = apps.get_model('payments', 'PaymentTransaction')
    for transaction in PaymentTransaction.objects.all():
        transaction.transaction_id = f"TXN{uuid.uuid4().hex[:12].upper()}"
        transaction.save(update_fields=['transaction_id'])


def reverse_transaction_ids(apps, schema_editor):
    """Reverse migration - no action needed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        # Step 1: Add field as nullable without unique constraint or index
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=100, null=True, blank=True, db_index=False),
        ),
        # Step 2: Populate existing records with unique IDs
        migrations.RunPython(generate_unique_transaction_ids, reverse_transaction_ids),
        # Step 3: Make field non-nullable (without unique constraint yet)
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=100, db_index=False),
        ),
        # Step 4: Add unique constraint
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=100, unique=True, db_index=True),
        ),
    ]