# Generated by Django 4.2.16 on 2026-09-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenttransaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='bank_rrn',
            field=models.CharField(blank=True, help_text='Bank Retrieval Reference Number (RRN) for UPI/Card transactions', max_length=100, null=True),
        ),
    ]